### ISSUE TITLE
Type Recipe with `plot([f,g], a, b)` notation

### ISSUE THREAD

**Issue by jverzani** [JuliaPlots/RecipesBase.jl#19] opened 2017-06-12 15:03 UTC
In `SymPy`, I had a recipe that used to work (quite awhile ago) to handle the case:

```
plot(Sym[x,x^2], a, b)
```

as though the symbolic expressions were functions. It was defined as:

```
@recipe f{S<:AbstractVector{Sym}}(::Type{S}, ss::S) = Function[lambdify(s) for s in ss]
```

The rhs side basically makes a collection of functions to pass along.

I can't figure out why this doesn't work. I suspect that the issue is in specifying the type to match in the `(::Type{S}, val::S)` part of the signature, but after trying several different things, am not so sure.

The debug info looks like:

```
apply_recipe args: Any[:x, :y, :z]
apply_recipe args: Any[:(::Type{T}), :(v::T)]
apply_recipe args: Any[:(::Type{T}), :(v::T)]
apply_recipe args: Any[:(::Type{T}), :(v::T)]
apply_recipe args: Any[:(::Type{SliceIt}), :x, :y, :z]
```

I know I can get this done by `plot` and `plot!`, but it would be nice to have this working again if it is possible. Any help would be most appreciated.

**Comment by mkborregaard** [comment] 2017-06-12 15:47
This makes me curious whether type recipes may not be working properly for things that are evaluated to functions? @jverzani do you need it to be a type recipe (i.e. do you need to also be able to pass x and y arguments like you can to functions, or would it be OK with a user recipe? 
```julia
@recipe f(ss::AbstractVector{Sym}) = [lambdify(s) for s in ss]
```
works.

**Comment by mkborregaard** [comment] 2017-06-12 15:52
For the record, the type recipe gives the error
```
ERROR: MethodError: no method matching min(::SymPy.Sym, ::Float64)
You may have intended to import Base.min
```
Which is reproducible by
```
using SymPy
@vars x
p = Sym(x^2)

f{S<:AbstractVector{Sym}}(::Type{S}, ss::S) = [lambdify(s) for s in ss]
f([p,p]) #gives the same error message
```
whereas
```julia
f(AbstractVector{Sym}, [p,p]) #the correct signature
```
works. So it looks like the type recipe isn't passing this properly forward?

**Comment by jverzani** [comment] 2017-06-12 17:06
Thanks for looking into this @mkborregaard . Unfortunately I don't see the graphs when I try the simpler user recipe you suggest. The `min` error must be fixed on master, as I don't see it here. My guess is like your more informed one: the type recipe isn't passing this forward properly. 

Here is a stripped down example, in case it helps track this down:

```
using Plots, RecipesBase
immutable Test <: Real end

@recipe f{T<:Test}(::Type{T}, v::T) = sin
#@recipe  f{T<:Test}(::Type{T}, ss::Vector{T}) = [sin,cos]
@recipe  f{T<:Test}(ss::Vector{T}) = [sin, cos]

plotly()
x1, x2 = Test(), Test()

plot(x1, 0, 1)
#plot([x1,x2], 0, 1)
```

**Comment by mkborregaard** [comment] 2017-06-12 17:26
I think the issue is that you can't actually define a type recipe on an Array{SomeType} - only directly on {SomeType}. You can define a user recipe on an array, but that fails in your example because if it's a user recipe it does not allow passing the 0 and 1 because it works differently from a type recipe (I guess the things you've commented out are those that don't work for you?).

**Comment by mkborregaard** [comment] 2017-06-12 17:29
Consider:
```julia
struct SymArray
       syms::AbstractVector{Sym}
end
@recipe f(::Type{SymArray}, ss::SymArray) = lambdify.(ss.syms)
a = SymArray(Sym[x, x^2])
plot(a, 0, 1)
```

**Comment by jverzani** [comment] 2017-06-12 17:35
Thanks, I feared that. At some point this setup worked, but it has been awhile since that time. I think rather than encourage a new type, I'll encourage the use of `plot` and `plot!`, which I prefer. This style is more for completeness in describing plotting as simply as saying use a symbolic expression where you would use a function.

**Comment by jverzani** [comment] 2017-06-12 17:36
Should this be left open as a feature request, or should I close it?

**Comment by mkborregaard** [comment] 2017-06-12 18:25
I think you can keep it open as a feature request, but there's perhaps a better option. I think the issue here is an inconsistency in how Functions are passed as plot arguments. For all other arguments, different series (lines) are passed as matrix columns. For Functions they are passed as a Vector{Function}. If Functions could be handled like other objects, you'd just need to define 
```julia
@recipe f(::Type{Sym}, s::Sym) = lambdify(s)
```
and then you could `plot([Sym(x^2) Sym(x^3)])`. Better Function parsing could be opened as a linked issue.

Note all of this is relevant to Plots, rather than RecipesBase, so the issue should be opened there. That repo is also watched by many more people.

**Comment by mkborregaard** [comment] 2017-06-12 18:42
I did some more checking and it fact it still does not appear feasible - so I'll just close this.

**Closed by mkborregaard** 2017-06-12 18:42 UTC
